-- Hosted Supabase only. Apply in the dashboard after CRON_SECRET is in Vault.
-- Staging Preview needs its own schedule: Vercel Cron runs only on Production.
-- Calls the protected worker to close due fights and drain notification outbox.
--
-- select cron.schedule(
--   'fitfight-scheduled-work-15m',
--   '*/15 * * * *',
--   $$
--   select net.http_post(
--     url := 'https://staging.fitfight.app/api/internal/close-fights',
--     headers := jsonb_build_object(
--       'Authorization',
--       'Bearer ' || (select decrypted_secret from vault.decrypted_secrets where name = 'cron_secret')
--     ),
--     body := '{}'::jsonb
--   ) as request_id;
--   $$
-- );
